language: objective-c
osx_image: xcode10.3
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
script:
  - xcodebuild -verbose -project ShortcutRecorder.xcodeproj -scheme ShortcutRecorder.framework -destination 'platform=macOS' build test
  - sed "s#  s\.source.*#  s\.source = \{ \:git => '$(pwd)' \}#" ShortcutRecorder.podspec > /tmp/ShortcutRecorder.podspec
  - pod spec lint /tmp/ShortcutRecorder.podspec --allow-warnings --verbose
  - carthage build --no-skip-current
  - file Carthage/Build/Mac/ShortcutRecorder.framework
after_success:
  - bash <(curl -s https://codecov.io/bash)
